# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  - trigger: ";dt"
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ";ts"
    replace: "{{ts}}"
    vars:
      - name: ts
        type: date
        params:
          format: "%Y-%m-%dT%H:%M:%S"
