#!/usr/bin/env bash

# This uses the `sesh` binary found here: https://github.com/joshmedeski/sesh#tmux--fzf

session=$(sesh list -i --tmux --zoxide --hide-attached | fzf-tmux -p 55%,60% -- \
  --ansi \
  --no-sort --border-label ' sesh ' --prompt '⚡ ' \
  --pointer '👉🏼' \
  --no-scrollbar \
  --layout reverse --info hidden \
  --header '^a all ^t tmux ^x zoxide ^f find' \
  --bind 'tab:down,btab:up' \
  --bind 'ctrl-a:change-prompt(⚡ )+reload(sesh list -i)' \
  --bind 'ctrl-t:change-prompt(🪟 )+reload(sesh list -ti)' \
  --bind 'ctrl-x:change-prompt(📁 )+reload(sesh list -zi)' \
  --bind 'ctrl-f:change-prompt(🔎 )+reload(fd -H -d 3 -t d -E .Trash . ~)')

sesh connect "$session"
