#!/usr/bin/env bash

# This uses the `sesh` binary found here: https://github.com/joshmedeski/sesh#tmux--fzf

session=$(sesh list -tz | fzf-tmux -p 55%,60% \
  --no-sort --border-label ' sesh ' --prompt '⚡  ' \
  --header '  ^a all ^t tmux ^x zoxide ^f find' \
  --bind 'tab:down,btab:up' \
  --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
  --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
  --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
  --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 3 -t d -E .Trash . ~)')

sesh connect "$session"
